version: "3.4"

services:
  web:
    build:
      context: .
      dockerfile: compose/Dockerfile
    container_name: async_web
    volumes:
      - .:/src
    ports:
      - 8000:8000
    command: ['sh', '-c', 'python3 main.py --host 0.0.0.0 --port 8000 --reload']

  db:
    image: postgres
    container_name: psql_db
    env_file:
      - ./compose/db_keys

  adminer:
    image: adminer
    container_name: async_admin
    ports:
      - "8080:8080"